[project]
name = "airtable-mermaid-grapher"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "networkx>=3.6.1",
    "pyscript>=0.3.3",
    "python-dotenv>=1.2.1",
    "typer>=0.9.0",
]
